# overridden properties for dev env
spring:
  jpa:
    show-sql: false
  mail:
    properties:
      mail:
        debug: false
  mattermost:
    webhook-url: "${MM_NOTIFICATION_URL:https://example.com/webhook}"
    time-tracker-url: "${TIME_TRACKER_URL:https://time-tracker.ru/}"